### ISSUE TITLE
PyPI release 1.7.1

### ISSUE THREAD

**Issue by jayvdb** [web-push-libs/vapid#85]
https://pypi.org/project/py-vapid/ is missing 1.7.1, which is a tag here
https://github.com/web-push-libs/vapid/releases/tag/1.7.1

**Comment by jrconlin** [comment]
Huh, not sure why. `twine check` comes back as the description as being valid, but I get a `400` from `pypi.org` saying the description is invalid. Not really sure why that is. 

I'll see if I can fix that later or chase down if it's a bug in pypi.

**Comment by peakengage** [comment]
Hey @jrconlin , we are also seeing a lot of invalid JWTs on our side using version 1.7.0. Would be great if the pip version is updated. 

Thanks!

**Comment by jrconlin** [comment]
<insert endless screaming here>

Right, so finally figured out the pypi problem. Posting here for anyone that also gets random
```
HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/
```
even though their current version passes `twine check`.

The problem is the old distributions. You know, the ones that are completely removed off of pypi. The ones that are still in your `/dist` or `/sdist` directory. Not sure why, but twine uploads those, and if there's anything wrong with those older versions it rejects the upload of the most recent one.

Because of course it does.

<more endless screaming here>

Anyway, 1.7.1 released.
